name: go matrix

on:

  push:
    branches: 
      - main
  workflow_dispatch:
  
      
jobs:
  Hello_World:
   strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: [1.13, 1.14, 1.15,]
  
  
   runs-on: ${{ matrix.os }}

   steps:
    - uses: actions/checkout@v3

    - name: Set up go
      uses: actions/setup-go@v3
      with:
       go-version: ${{ matrix.version }}
         
    - name: Build
      run:  go build -v ./...

    - name: Test
      run:  go test -v ./...