name: go Hello world

on:
  workflow_dispatch:
    inputs:
      goversion:
        description: "Go Versions"
        required: true
        type: choice
        options:
        - "1.15"
        - "1.14"
        - "1.13"

jobs:
  test1:
   strategy:
      matrix:
        version: [10, 12, 14, 18]
        os: [ubuntu-latest]
  

   runs-on: ${{ matrix.os }}

   steps:
     - uses: actions/checkout@v3

     - name: Set up go
       uses: actions/setup-go@v3
       with:
         go-version: ${{ inputs.goversion }}
         
     - name: Build
       run:  go build -v ./...

     - name: Test
       run:  go test -v ./...